### ISSUE TITLE
Use IOKit to Create /dev Entries for Every ZFS Dataset

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#116]

**Comment by ilovezfs** [comment]
Volume rename also needs /dev/disk* entries in order to be enabled in Finder.
https://github.com/openzfsonosx/zfs/issues/273

**Comment by samvv** [comment]
Just wondering: what is the current status of this issue? Is there any progress?

**Comment by lundman** [comment]
"issue116_manual" is the snapshot I am working on, the /dev nodes part works, and snapshots can automount. But ZVOLs at the moment can not be unmounted. It is being worked on when convenient :)

**Comment by samvv** [comment]
Awesome, thanks!

Keep up the good work!

Jorgen Lundman <notifications@github.com>schreef:

**Comment by dabrahams** [comment]
Slight bump, a year later.  Any progress/anything I can do to help?

**Comment by lundman** [comment]
This is currently in branch "issue116_manual" and works, if a little roughly. The snapshots sort of mount automatically, but sometimes too late for the triggering process. The zfs_boot is based on this branch, although I noticed I failed to create a fake entry for the boot device. I will fix that soon

**Comment by dabrahams** [comment]
I’m not sure which snapshots or triggering process you’re talking about.  Care to elucidate?

Thanks!

**Comment by lundman** [comment]
Lesse now, when access inside ".zfs/snapshot/" is detected, `zfs_ctldir.c` triggers a mount (read-only) of that snapshot automatically.
https://github.com/openzfsonosx/zfs/blob/issue116_manual/module/zfs/zfs_ctldir.c#L1413

But being second class citizens in the XNU kernel, there just is no way for us to call `mount` from the kernel. Not even the special helper for NFS - which is a shame, since Apple could have shown how they want us to do kernel mount here. Why does NFS get to cheat! :)

So we create a new fake /dev/disk entry, with contentHint that matches, `zfssnapshot.fs` bundle, which (eventually), calls `mount` on it, and we come back into the kernel. We can then release the process that caused it all to start.
https://github.com/openzfsonosx/zfs/blob/issue116_manual/module/zfs/zfs_osx.cpp#L777

As you can see, it is pretty half-cooked and icky (it even just calls `delay` rather than using condvars to signal mount successful).

**Comment by ilovezfs** [comment]
I wonder if we should file an rdar about the NFS "cheating" since this workaround seems totally unnecessary.

**Comment by dabrahams** [comment]
on Wed Jun 22 2016, ilovezfs <notifications-AT-github.com> wrote:

> I wonder if we should file an rdar about the NFS "cheating" since this
> workaround seems totally unnecessary.

Radars are good :-)

-- 
Dave

**Comment by dabrahams** [comment]
Thanks for the explanation. Auto-mounting snapshots is not high on my list of priorities so maybe I'll pursue this angle and see where it leads.

**Comment by ilovezfs** [comment]
@dabrahams which angle do you mean?

**Comment by dabrahams** [comment]
@ilovezfs I mean trying the branch as a way to get Backblaze to recognize the filesystems and actually back them up.

**Comment by ilovezfs** [comment]
@dabrahams did you get a chance to try what Michael Newbery suggested?
https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2787&p=7180&hilit=Backblaze#p7186

**Comment by jessiebryan** [comment]
@dabrahams, @ilovezfs, I use o3x and Backblaze. Backblaze does not officially support backing up a ZFS dataset, however, their file scanner does include these files as part of my root volume backup. I have verified that my datasets mounted under /zfs/* and /Users/jbryan/Dropbox are backed up, and can be restored. Datasets mounted under /Volumes/* do not get backed up, regardless if you allow /Volumes* in your Backblaze Preferences.


Screenshots:
 1) Backblaze restore http://prntscr.com/bp784v

ZFS Info:

	m83:/ root# zfs list
	NAME                  USED  AVAIL  REFER  MOUNTPOINT
	  zpool              14.5T  6.59T   540K  none
	  zpool/Dropbox       210G  6.59T   210G  /Users/jbryan/Dropbox
	  zpool/Movies1      6.08T  6.59T  6.05T  /zfs/Movies1
	  zpool/PLEXMETA     31.0G  6.59T  31.0G  /Volumes/PLEXMETA
	  zpool/Photos1       192G  6.59T   192G  /zfs/Photos
	  zpool/TV-Active    4.64T  6.59T  4.10T  /zfs/TV-Active
	  zpool/TV-Ended     3.16T  6.59T  3.04T  /zfs/TV-Ended
	  zpool/WHITELINER1   183G  6.59T   183G  /zfs/WHITELINER1
	  zpool/cfg1          935M  6.59T   935M  /zfs/cfg


In the list above, my "/Volumes/PLEXMETA" is not included in Backblaze backup. The workaround here is to adjust the ZFS dataset mountpoint path:

	sudo zfs set mountpoint=/zfs/PLEXMETA zpool/PLEXMETA

In case you want to use Dropbox over a ZFS Dataset + Backblaze:

	sudo zfs set mountpoint=/Users/${USER}/Dropbox zpool/Dropbox

You would need to do this for each dataset you want Backblaze to backup. Backblaze does not consider these as separate volumes, they just attach to the root volume, and that's OK for me.

**Comment by dabrahams** [comment]
@jessiebryan Such a simple answer, and it works!  Amazing, thank you!

**Comment by lennonolium** [comment]
@jessiebryan @dabrahams 

Is that solution still working for you? Backblaze isn't traversing /zfs for me (same perms as /Volumes). I'm wondering if I need to remove the computer and try doing another full backup to BB.

**Comment by dabrahams** [comment]
@lennonolium yes it's working for me

**Comment by lennonolium** [comment]
@dabrahams, thanks. I should have updated last night. After changing mount points to a similar strategy, I would force BB to conduct a backup, but it wouldn't pick up the new /zfs/... subdirectories. I sat here for hours tweaking various dataset parameters. Then, I woke up this morning and it had started syncing. Ha! All 7TB up on BB and living on ZFS. No problem at all.

**Comment by Technofrikus** [comment]
@jessiebryan Thank you very much for the mountpoint idea! I had to reinstall Backblaze because it did not recognize the folder at first and said the backup was complete, even though it was not, not even without the zfs-folder (but this might be another problem of Backblaze and unrelated). But now it works perfectly and uploads. Now I just have to wait forever to complete the large upload :P

**Comment by mauricev** [comment]
I use arq to access Backblaze B2 storage (as well as Wasabi). Arq sees zfs datasets natively.

**Comment by JMoVS** [comment]
@lundman I think as issue116lite was merged, this can be closed...
