### ISSUE TITLE
race condition / deadlock showing up at dnode_special_close

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#137]
```
 ssh o3x.org zfs send -R o3xpool@1396051829 | sudo zfs recv -F o3xpool
```

http://bpaste.net/show/196813/

**Comment by lundman** [comment]
Looking at the code:
```
getzfsvfs(const char *dsname, zfsvfs_t **zfvp)
{
...
        *zfvp = dmu_objset_get_user(os);
        if (*zfvp) {
                VFS_HOLD((*zfvp)->z_vfs);
```

and uses of it, like that of zfs_ioc_recv:
```
	if (getzfsvfs(tofs, &zfsvfs) == 0) {
		ds = dmu_objset_ds(zfsvfs->z_os);
		error = zfs_suspend_fs(zfsvfs);
		VFS_RELE(zfsvfs->z_vfs);
```

So it appears that `getzfsvfs()` will grab the `zfsvfs` while under `dmu_objset_hold()` lock, then lock the VFS by calling `VFS_HOLD()`. Once we are done with `zfsvfs` it calls `VFS_RELE()`.

On O3X, both `VFS_HOLD` and `VFS_RELE` are empty defines, as we do not have anything directly like IllumOS versions.

Even though the IllumOS comment for `VFS_HOLD` sounds somewhat benign, it would appear that it will stop unmounts from happening. Whereas for us, unmount can happen, and `z_os` is released (possibly reused by something else) so our `zfsvfs` will be over-written by random garbage (as well as us using `zfsvfs` after it was freed).

Our closest call to `VFS_HOLD` appears to be `vfs_busy`, but there are some implementational differences.

IllumOS `VFS_HOLD` is an atomic operation, and can therefore be called repeatedly. A good example of that is zfs_vfsops.c calling it, and calls `zfsctl_create` which also call it from `gfs.c`, which in turn calls `getroot` and we end up in zfs_znode which call it a third time.

On OSX you can only call it once, any nesting calls will deadlock.

A second issue is that even when calling `vfs_busy( , LK_NOWAIT)` it only detects when unmount is happening, and returns immediately. It does not include mounting, so we can not call `vfs_busy` from within the `zfs_vfs_mount()` context. (which is where `zfsctl_create()` is call as above.)

So we can add #ifdef APPLE `vfs_busy()` calls around the functions that call `getzfsvfs()` (there are 5).
Or we can attempt to make VFS_HOLD, use `mount_fsprivate()` to get the `zfsvfs` ptr, and store an atomic in the struct. And upon reaching `1` (or `0`) in `VFS_HOLD` (`VFS_RELE` respectively) call `vfs_busy` (`vfs_unbusy`). With the additional hack that `zfs_vfs_mount()` creates `zfsvfs` with the atomic already at `1` since we may not call `vfs_busy` at this time (nor do we need to, it is locked to call us).

**Comment by JMoVS** [comment]
@lundman Or is this still an issue?
