### ISSUE TITLE
iscsi support?

### ISSUE THREAD

**Issue by dabrahams** [openzfsonosx/zfs#276]
Hi,

I've been really impressed with O3 so far, but I notice it doesn't seem to support shareiscsi:

```
$ zfs set shareiscsi=on zig/tm
cannot set property for 'zig/tm': invalid property 'shareiscsi'
```

Is iscsi support in the plan?

**Comment by evansus** [comment]
@dabrahams On other platforms the shareiscsi property communicates with an iSCSI target daemon to enable or disable sharing on individual zvols. ZFS itself does not provide an iSCSI target or initiator, just the configuration of new devices for external software.
Since Mac OS X does not have either a built-in or open-source iSCSI target, there isn't an easy option for this. This would require something like SNS GlobalSAN Xtarget (msrp $899). Or more ideally, an open-source iSCSI target for OS X.

In my opinion we should hide the shareiscsi property since it (at this time) is unusable. Ditto for sharesmb, although we could implement `zfs set sharesmb=on` using the [sharing (1)] (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sharing.1.html) util.

**Comment by lundman** [comment]
We have not implemented any of the sharing properties, NFS, SMB, AFP and iSCSI. At the moment, you setup your dataset/volume, then use the OS way to share it.

We can probably implement NFS/AFP, and SMB though, one day.

**Comment by dabrahams** [comment]
Ah, thanks for explaining!
