### ISSUE TITLE
If device resets or gets disconnected, zpool command gets locked up until reboot

### ISSUE THREAD

**Issue by claunia** [openzfsonosx/zfs#285]
Operating system: Mac OS X 10.10.0, Mac OS X 10.9.5, Mac OS X 10.9.2
O3X: 1.3.1RC5, 1.3.0, 1.2.7
How to reproduce: Create a pool on an USB device, unplug it without umount or export.
Behaviour: pool keeps appearing. zpool command gets instantly locked on execution. zfs command keeps working. reboot needed to solve this pool problem (or to import/export any other pool)
Expected behaviour: pool moves to DAMAGED or MISSING (don't recall exact zfs terms), vnode also, zpool command keeps working, as happens on Linux for example.
Desired behaviour: on reconnection O3X detects the pool the devices belongs to and solves the problem.

**Comment by ilovezfs** [comment]
Do the behaviors change at all if you have set failmode=continue before it happens?

**Comment by ilovezfs** [comment]
This should be fixed in most cases by https://github.com/openzfsonosx/zfs/commit/8c55b29781836f8cb63e5aab361d1647e221f097

If we can isolate specific failures cases not handled by https://github.com/openzfsonosx/zfs/commit/8c55b29781836f8cb63e5aab361d1647e221f097, then we can address those individually.

Please note that after reconnecting a disconnected device, you will need to issue zpool clear, just as you would on Solaris/illumos and other OpenZFS platforms.
