### ISSUE TITLE
Invariant Disk not ready when using Areca Controller

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#312]
In combination with an Areca ARC-1320 Controller, the Invariant Disks are not ready when using the default plist settings.

Only with
        <key>ProgramArguments</key>
        <array>
                <string>/usr/sbin/InvariantDisks</string>
                <string>-t</string>
                <string>16000</string>
        </array>

it is working.

This results in log or cache device beeing unavail when running on the Areca Controller and other diskpaths beeing randomly chosen from /dev or /var/run/disk/by-id 

I suggest to expand the timeout as a default setting or to implement some kind of doublecheck to detect if InvariantDisk is finished with import/symlink creation.

**Comment by ilovezfs** [comment]
The four second default definition of idleness has so far seemed suitable for most use cases. Increasing it would mean delaying pool import for everyone else, including those for whom four seconds has been plenty.

The purpose of -t was exactly so that you could do what you did if you found four seconds to be insufficient.

Also, you may want to change https://github.com/openzfsonosx/zfs/blob/41202a19c89c917ab6e19e41fc95f044d48ff6c9/etc/launchd/launchd.d/zpool-import-all.sh.in#L31

from
```
"${ZPOOL}" import -a
```
to
```
"${ZPOOL}" import -a -d /private/var/run/disk/by-id
```

**Comment by mruepp** [comment]
The kernel dev should already be populated when launchd is run by the kernel. So what I don´t understand is why InvariantDisk takes such a long time populating the /var/run/disk folder, it should not be depending on the Areca Controller to finish initializing because the areca kext is loaded and initialized already in the Bootloader sequence and kernel devs are established. 
Maybe pool import should depend on successful return of InvariantDisk Daemon.

I suggest thinking about a programatic solution and consider this a bug (but low priority) as long as one has to edit files on every update of the zfs stack.

**Comment by ilovezfs** [comment]
Idleness is defined as no incoming notification callbacks to the InvariantDisks daemon. So four seconds of idleness means the InvariantDisks daemon is happily sitting there doing nothing, and not being asked to do anything, for four seconds. It has returned successfully. That's the point. It's done.

So if you're having to increase the idleness time, it's because you're hardware wasn't initiating contact with disk arbitration within that four second window.

**Comment by mruepp** [comment]
So is Invariantdisk daemon listening to DARegisterDiskAppearedCallback and if there is a new disk appearing is updating /var/run/disk? 

What actually is the -t option then doing if the daemon is listening to the callback method?

**Comment by ilovezfs** [comment]
It's creating and removing, creating and removing, the invariant.idle file. It creates it if it's been doing nothing for four seconds, and removes it whenever a disk appears or disappears:
https://github.com/cbreak-black/InvariantDisks/blob/master/InvariantDisks/IDDAHandlerIdle.cpp

Yes, it's listening to DARegisterDiskAppearedCallback, as well as DARegisterDiskDisappearedCallback:
https://github.com/cbreak-black/InvariantDisks/blob/master/InvariantDisks/IDDiskArbitrationDispatcher.cpp#L34-L42

The consumer of invariant.idle file is the spool-import-all.sh script:
https://github.com/openzfsonosx/zfs/blob/master/etc/launchd/launchd.d/zpool-import-all.sh.in#L13-L18

It blocks until the idle file exists, but will give up after sixty seconds (configurable at the top of the script as TIMEOUT_SECONDS).

**Comment by mruepp** [comment]
Works with -t 32000. Still not convinced this is a "Macish" Solution. There should be definitely no fiddling around in config files. I run a quite default setup. It seems the Areca takes some time to recognize the devices so the invariant idle file gets deleted before all the disks are recognized. This I observed when zfs is not installed. After logon, the "New Disk blabla, initialize or ignore" messages pop up after a while.

**Comment by cbreak-black** [comment]
There's not much more InvariantDisk can do. The processing should be extremely fast (ID doesn't do much), but if the OS doesn't tell me about it then all I can do is assume the system is idle.
