### ISSUE TITLE
Best way to provide stack traces or debug info for deadlocks involving the vfs?

### ISSUE THREAD

**Issue by vmrob** [openzfsonosx/zfs#417]
I've been using ZFS regularly and am keeping a sharp eye out for updates, but am still exposed to symptoms that look very similar to the issues described [here](https://github.com/openzfsonosx/zfs/issues/395) even after upgrading to 1.4.5.

What's the best way to provide debug info that can help diagnose this?

**Comment by lundman** [comment]
If you are close-to-but-not-quite-dead, you can run `spindump`, which takes 10s worth of kernel snapshot of stacks. When we were leaking memory and I was close to being dead, it took nearly 20mins to get a spindump through. It will write to /tmp, which is generally a memory filesystem, so that the deadlocked filesystems should not get in the way. The trick is either to cat and capture the output or hope you can scp/wgetpaste the file off the machine.

A little more advanced way, if you have a second mac (or VM running osx) you can NMI the kernel, and connect with lldb. Dump stacks and other goodies.

Thirdly, we could be leaking memory still, which has that bogged-down-ending-with-beachball feel to it, you can run ZFS as-close-as-you-can to when it gets unusable then;

```
# export all your pools
zpool export $pool   
# unload zfs.kext
kextunload -b net.lundman.zfs   
# make SPL reap and drain memory caches
sysctl -w kstat.spl.misc.spl_misc.simulate_pressure=1 
# double check memory caches are 0  
sysctl kstat | grep kstat.unix.kmem_cache.kmem_alloc_ | grep inuse
```

All the inuse buffers should be 0. If not, we are leaking.
