### ISSUE TITLE
zfs rollback doesn't work in Finder until zfs dataset remounted

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#463]
Here is what I did:

````
sudo zfs create tank/test
````
switch in Finder to the new dataset. Put a folder on the top level **and** put a folder/file inside it.

Now:
````
zfs snap tank/test@before
````
go to Finder. Delete the top level folder.

Now back to Terminal:
````
sudo zfs rollback tank/test@before
````
Switching back to FInder first shows nothing, then switching to the mountpoint again shows me the top level folder but doesn't allow me to peak inside it. And sometimes the top level just disappears again. All this is mitigated by running zfs unmount and then mount on the dataset.

I am **not** a 100% sure but if I remember that last time I needed it correctly, this used to work, but as I said, I'm not sure. I am on latest master.

**Comment by lundman** [comment]
Need to know if you can make Finder to refresh, if you use Finder to create a new directory.

**Comment by JMoVS** [comment]
nope, creating a directory using Finder doesn't work. In fact, the folder (test) just has the icon of a file but a triangle to the right indicating it being a folder yet I am unable to look into it.

![image of file iconed folders](http://cl.ly/f8Ya/Bildschirmfoto%202016-02-15%20um%2009.14.51.png)

**Comment by lundman** [comment]
fc6a9ca9240053ed456c6acad7aceaf54e5de789

**Comment by JMoVS** [comment]
could this method be used as well for issue https://github.com/openzfsonosx/zfs/issues/436 (why is that still open?)

**Comment by ilovezfs** [comment]
JMoVS, it should probably be closed. However, I think both issues need to be verified as fixed in a multi-user environment when two or more users are logged in at the same time, each able to see and access the same mounted file system (e.g., when ignore owners is on). Does Finder get the updates, etc. and avoid the rollback issue in all workspaces or is one or more still broken? It would be great if you could check that.
