### ISSUE TITLE
zpool  kernel  panic on  boot after upgrade to 10.11.4

### ISSUE THREAD

**Issue by diekhans** [openzfsonosx/zfs#471]
After upgrading to El Capitan 10.11.4 15E65, zpool kernel module panics on boot.

These are external thunderbolt connected drives.  If I disconnected the drivers and
boot, then reconnected, they import and are usable without problem.

Kernel panic information and zpool status attached.

[zpool.status.txt](https://github.com/openzfsonosx/zfs/files/187228/zpool.status.txt)
[zfs-crash.txt](https://github.com/openzfsonosx/zfs/files/187225/zfs-crash.txt)

**Comment by ilovezfs** [comment]
And it's repeatable?

**Comment by diekhans** [comment]
Repeated three times reliably.  Happy to help debug, systems programmer, but not  a mac  systems programmer.

**Comment by ilovezfs** [comment]
Can you try with https://openzfsonosx.org/wiki/File:O3x-1011-signed-spl-12a3476-zfs-af351b2.pkg please

**Comment by diekhans** [comment]
Works like a champ.  Two reboots, zero problems. Thanks a lot @ilovezfs

**Comment by ilovezfs** [comment]
@diekhans Great, thanks. It would be nice to know exactly what fixed it, but if it's fixed, it's fixed.

**Comment by ilovezfs** [comment]
@diekhans OK, this is why it's fixed:
zfsonlinux/zfs#3370
zfsonlinux/zfs@ff9b1d07256c57b607cc6ad3448c1fb2487305d6

which we now have, too:
ff9b1d07256c57b607cc6ad3448c1fb2487305d6

There's an upstream PR for this fix as well now:
https://github.com/openzfs/openzfs/pull/19

Due to behlendorf's suspicions in zfsonlinux/zfs#3370 and since it's best practice anyway, I'd recommend you export and reimport -d /var/run/disk/by-id or -d /var/run/disk/by-serial
https://openzfsonosx.org/wiki/Device_names
