### ISSUE TITLE
zpool create will destroy other filesystem without -f in zpool create

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#488]
zpool_create_002_pos.ksh is a test that currently fails. Aside from having a few porting issues, it requires that zpool create without -f fails to destroy an existing filesystem. 

Whole disk case:

sudo diskutil eraseVolume hfs+ something /dev/disk2
Started erase on disk2
Unmounting disk
Erasing
Initialized /dev/rdisk2 as a 20 GB case-insensitive HFS Plus volume
Mounting disk
Finished erase on disk2 something
big-vm-mac-imac:zfs-test zfs-tests$ sudo diskutil unmountDisk something
Unmount of all volumes on disk2 was successful
big-vm-mac-imac:zfs-test zfs-tests$ sudo zpool create tank disk2
big-vm-mac-imac:zfs-test zfs-tests$ sudo zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	tank        ONLINE       0     0     0
	  disk2     ONLINE       0     0     0

Partition case:

diskutil list
/dev/disk0 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *536.9 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            536.0 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *21.5 GB    disk1
   1:                        ZFS                         21.5 GB    disk1s1
   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk1s9
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *21.5 GB    disk2
   1:                        ZFS                         21.5 GB    disk2s1
   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk2s9
/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *21.5 GB    disk3
   1:                        EFI EFI                     209.7 MB   disk3s1
   2:                  Apple_HFS freddo                  10.6 GB    disk3s2   <---- HFS Formatted
   3:                  Apple_HFS Untitled                10.4 GB    disk3s3
big-vm-mac-imac:zfs-test zfs-tests$ sudo diskutil unmountDisk disk3
Unmount of all volumes on disk3 was successful
big-vm-mac-imac:zfs-test zfs-tests$ sudo zpool create tank2 disk3s2
big-vm-mac-imac:zfs-test zfs-tests$ zpool status
  pool: tank2
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	tank2       ONLINE       0     0     0
	  disk3s2   ONLINE       0     0     0

**Comment by ilovezfs** [comment]
This is a critical bug caused by our lack of Linux's libblkid. The problem occurs when we return here:

https://github.com/openzfsonosx/zfs/blob/master/cmd/zpool/zpool_vdev.c#L459-L460

The partition type checking that happens lower down in check_disk never runs (nor should it since this is a partition not a whole disk), and there's no corresponding code like that in check_slice or check_file. On Linux, there is corresponding code like that when you have libblkid, which they've recently made a hard requirement. So we just go down the very unsafe no libblkid code path, and do zero checks. On illumos there is elaborate in-use checking, which goes well beyond the simple partition type checking or the libblkid checking Linux has.

At minimum in the short-term we should consult the partition table, but that does nothing to resolve the problem when there's no partition table (e.g., Core Storage logical volume). So we need something more robust that will actually consult iokit/diskutil/diskarb/disk framework/etc. and do the appropriate checks even without a partition table or with mismatched partition table types.

**Comment by lundman** [comment]
Would reading from the device and doing matching similar to /etc/magic work here, or do Core Storage not leave any hints at all on the device?

**Comment by ilovezfs** [comment]
All the info is available in diskutil/iokit. The simplest hack is /Systems/Library/Filesystems/hfs.fs/Contents/Resources/hfs.util -k diskAsN for an hfs partition and -k diskA for an hfs logical volume. The trickier case is a core storage physical volume (the partition that is the backing store for the logical volume) which won't respond to hfs.util -k, but the partition type for those will almost always be correct.

The corner cases that require a more correct disk framework based approach are those where the partition type is wrong, which will be true whenever, for example, the user follows a procedure for a non-whole-disk vdev and sets the partition type to zfs first (assuming we were actually doing that check which we're not) but does so with the wrong device. In other words, they would get screwed if and only if they followed directions and protected if and only if they did not follow directions.

This is one of the reasons that no other platform relies on partition type alone as a guide.

Also there is the case of non-hfs file systems, so we'd have to probe with their foo.util -k too, or leave those unprotected whenever their partition type is wrong.

But all of the hacks including relying on partition tables are silly since iokit and disk framework have already done all of this probing and publish the information with programmatic interfaces that are at least as good as those available for liblkid (Linux), geom (FreeBSD), and disk management (illumos).

**Comment by ilovezfs** [comment]
Another problem is that hfs.util requires root privileges so readonly dry runs would require sudo or not notice the problem, whereas iokit/disk framework/diskutil do not require root, and would get the answer correct for readonly sudo-less dry runs.

**Comment by ilovezfs** [comment]
These are the checks always performed by illumos on a slice:
```
static detectorp detectors[] = {
	inuse_mnt,
	inuse_svm,
	inuse_active_zpool,
	inuse_lu,
	inuse_dump,
	inuse_vxvm,
	inuse_exported_zpool,
	inuse_fs,  /* fs should always be last */
	NULL
};
```
https://github.com/illumos/illumos-gate/blob/139510fb6efa97dbe5f5479594b308d940cab8d1/usr/src/lib/libdiskmgt/common/slice.c#L57-L67
https://github.com/illumos/illumos-gate/blob/28b6fd27d5ff75fe6fdeb119a21575b0652a7e70/usr/src/cmd/zpool/zpool_vdev.c#L146

We do zero checks.

**Comment by brendonhumphrey** [comment]
@ilovezfs I am currently writing a libdiskmgt (lite) for us, and I intend including some form of fs probing. One possible approach would be based on the code for 'disktype' (http://disktype.sourceforge.net/). Are you able to elaborate on what you were thinking with iokit etc, or were you just thinking of parsing the output of diskutil?

**Comment by brendonhumphrey** [comment]
Closed in favour of https://github.com/openzfsonosx/zfs/issues/489

**Comment by brendonhumphrey** [comment]
https://github.com/openzfsonosx/zfs/commit/dd75914a024878541370640078dc3690a4e59e0b
