### ISSUE TITLE
memory leak in vdev_config_generate_stats

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#536]
rottegift reports that this command will leak:

```
while [ 1 ] ; do zfs hold tag BOOM@nonexistent; done

kstat.unix.kmem_cache.kmem_alloc_256.buf_inuse: 0
kstat.unix.kmem_cache.kmem_alloc_256.buf_inuse: 3960
kstat.unix.kmem_cache.kmem_alloc_256.buf_inuse: 4680
```

and never released.

This can be stopped by removing;

`vdev_label.c` vdev_config_generate()
```
    if (getstats) {
        pool_scan_stat_t ps;

      //   vdev_config_generate_stats(vd, nv);

        /* provide either current or previous scan information */
        if (spa_scan_get_stats(spa, &ps) == 0) {
```

but that causes slight panics in `spa_add_l2cache()`

This came in from;

    commit 193a37cb2430960ce759daf12ce5cc804818aba1
    Add -lhHpw options to "zpool iostat" for avg latency, histograms, & queues

which may be from a porting issue.

**Comment by rottegift** [comment]
At least some of that is this, which I found by poring over code.  Turns out ZoL has this fnvlist_free:

https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev_label.c#L349

and we do not.   Result: one leak per _stats configuration, and that happens when the spa config is synced (e.g. when we do a hold, or when a vdev is added or removed) or when we prep a reply for a "zpool iostat".

Also found while writing this:

https://github.com/zfsonlinux/zfs/commit/6a7967253064a0b8711ca746a1296ee6439d36e6

which should just be pulled in from there.
