### ISSUE TITLE
ZFS io error

### ISSUE THREAD

**Issue by Bleistein** [openzfsonosx/zfs#632]
We upgraded a Mac mini (2011) + AKiTiO Thunder2 Quad Mini in raidz0 (native encrypted) configuration from openzfsonesx 1.7.0 to 1.7.1.

Handling the zpool seems to work ok, even *scrubbing* is possible. Trying to mount the zfs filesystem (native encrypted) results in i/o errors:

```
$ sudo zfs mount -a
Password:
cannot mount 'raid/shared/archive': Input/output error
cannot mount 'raid/shared/etc': Input/output error
cannot mount 'raid/homes/mb': Input/output error
cannot mount 'raid/shared/media': Input/output error
```

Reinstalling 1.7.0 gave a working system again!

**Comment by lundman** [comment]
Actually, that should say read-only. The on-disk format changed, so I believe you should be able to zfs send | zfs recv  to convert to new format.

**Comment by cbreak-black** [comment]
zpool status should tell you that this is an intended error. Mounting normally fails, but zfs send | zfs receive to a new pool (or newly created encrypted dataset) works.

I transferred my old native pool to a new one with zfs send. Unfortunately, replication streams don't work without raw sending, which doesn't work in this case since raw sending is broken with the old on-disk format. So you have to send all filesystems one by one. If you want to preserve snapshots, I recommend sending the oldest snapshot on each dataset manually, and then sending the newest one with -I (which sends all intermediate snapshots).
