### ISSUE TITLE
1.7.3 beta causes boot loop on Mojave Developer Beta 1 and 4

### ISSUE THREAD

**Issue by as-com** [openzfsonosx/zfs#644]
I installed 1.7.3 on my rMBP (13-inch, Mid 2014), and when I rebooted, the Apple logo would appear for half a second after entering my FileVault password with the progress bar nearly filled, then reboot again.

I cannot find any kernel panic/crash logs related to this issue.

**Comment by ylluminate** [comment]
Any news on this? I'm getting ready to start running Mojave myself to do some testing and dev work so I'd like to know where we stand.

**Comment by as-com** [comment]
@ylluminate I'm using 1.7.2 for now, it seems to work fine. I haven't tried 1.7.3 BETA for any of the other Developer Previews.

**Comment by ylluminate** [comment]
Just need to fix that dash in there:
`sudo nvram boot-args="-show_pointers -v keepsyms=y debug=0x144"`

**Comment by lundman** [comment]
Does it still panic on mojave for anyone?

**Comment by as-com** [comment]
Yes it does... and this time I have a backtrace, in video format! (I can’t find them on disk)

4K 60 FPS: 
https://drive.google.com/open?id=1nj4QM9K1eLc1VB8sjh_jbQFj7VXJPzA9
1080p 240 FPS: 
https://drive.google.com/open?id=1UYV5OUCmyPQpO4jPESnG24AnuS1tX_3l

Yes, you will need to step through these frame by frame to see the whole thing.

**Comment by lundman** [comment]
Well, that's just more confusing :)  So it dies loading SPL, during the early init
```
spl_start()
 -> spl_kmem_thread_init()
    -> taskq_create()
      -> taskq_create_common()
        -> taskq_thread_create()
          -> spl_cv_wait() 
            -> msleep()

  panic cpu(2) type 14 page fault
```
The exact call is:
```
	mutex_enter(&tq->tq_lock);
	while (tq->tq_nthreads != tq->tq_nthreads_target &&
	    tq->tq_nthreads < TASKQ_CREATE_ACTIVE_THREADS) {

		cv_wait(&tq->tq_wait_cv, &tq->tq_lock);
-------------------^
```

which ends up calling `msleep()`. Interesting to note here is that `tq_wait_cv` is just an address it uses to match (does not dereference), and `tq_lock` is already held in the previous `mutex_enter()` call, so we know both addresses are "valid".

The size of `lck_mtx_t` is still 16 in mojave, and has not changed. 

I'm assuming it isn't some brand spanking new hardware, so no changes there.

**Comment by lundman** [comment]
and I am right in assuming that spl will load by hand, just not from boot?

**Comment by lundman** [comment]
Alas we do not have the kernel sources for mojave yet, but if things haven't changed, we are
getting into trouble at:
`_sleep + 0x63` video is a bit blurry, but I think its 0x63 (+99 decimal).
```
(lldb) dis -a _sleep
kernel`_sleep:

kernel[0xffffff80008ce3e8] <+88>:   je     0xffffff80008ce3f2        ; <+98> at OSAtomicOperations.c
kernel[0xffffff80008ce3ea] <+90>:   lock
kernel[0xffffff80008ce3eb] <+91>:   incq   0x80(%rax)
kernel[0xffffff80008ce3f2] <+98>:   movl   %r14d, %esi
kernel[0xffffff80008ce3f5] <+101>:  andl   $0x400, %esi              ; imm = 0x400
```

which means we are dying in a call to `OSAtomicOperations` and looking at 10.13 sources the code is
```
        p = current_proc();
        p->p_priority = pri & PRIMASK;
        /* It can still block in proc_exit() after the teardown. */
        if (p->p_stats != NULL)
                OSIncrementAtomicLong(&p->p_stats->p_ru.ru_nvcsw);
```

Now, `current_proc()` will never return NULL, it will at very least return kern_proc. But I am uncertain as to how `p_stats` is handled.

If the trouble is that we load too early in the process, we could easily test that hypothesis by changing the priority:

```
diff /Library/Extensions/zfs.kext/Contents/Info.plist
        <key>OSBundleRequired</key>
-        <string>Root</string>
+        <string>Local-Root</string>
```
for slightly later, or remove entirely for no boot load.
Followed by `touch /Library/Extensions/zfs.kext`
to make it reindex the kexts for reboot.

**Comment by lundman** [comment]
Ok, what is the level of dev here?

* Can I provide branch, and people can build and test?
* Or spl.kext binary ?
* And does it have to be signed?

I'd like to have confirmed that if /Library/Extensions/spl.kext is deleted, that spl.kext can be loaded by hand after a boot:

* mv /Library/Extensions/spl.kext /var/tmp/
* reboot
* kextload /var/tmp/spl.kext

**Comment by lundman** [comment]
branch 'mojave' in spl. No rush, I'll upgrade my macbook air at work and see if I can't trigger it myself. The VMs certainly do not trigger.

**Comment by lundman** [comment]
Ok, it is indeed that we are "way too early" to start using some parts of the kernel on "fast hardware". Since I can detect it, I have put in a delay at startup which solves the problem on my hardware.
Meanwhile, I'll wait and see if Apple has a better way to handle this race.

e50bbc3d534d1305aed91fe2d94b60793a246b9a

But it will now work on mojave.

**Comment by ylluminate** [comment]
So I just had a panic in Mojave after it was booting just fine for the past several days.  I updated to beta 8 and it booted - no problems.  I had a strange issue with my video card (bug with my model that I'm troubleshooting with Apple and due to this, I didn't have my bar screwed in on my Mac Pro and so when I unplugged the cable, my USB 3 card unplugged and hung the system), so I had to hard power off the system (held power in for 5 sec to kill it).  When I brought the system back up, it wouldn't boot.

I tried a few more reboots, nothing.  I then had to plug in a non-Metal Apple EFI capable card and on verbose boot I found the system was panicked on ZFS loading. I'm still dealing with just trying to get my system up right now (safe mode is not loading up any appreciable speed; apparently APFS hung on "checking snapshot 1 of 1" now for about 30 minutes).  But I thought I'd share a picture of the panic that I've gotten to see so far:

![panic](https://cl.ly/c8288fc921de/IMG_8610.JPG)
